import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";

import DashboardWrapper from "@/app/DashboardWrapper";

import React from 'react';



const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight:"400"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
                 <DashboardWrapper>{children}</DashboardWrapper>    
      </body>
    </html>
  );
}
